In [148]:
from numpy import random
import numpy as np

## Exercici 1
Creamos una funció que donat un Array d’una dimensió, fa un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

Creamos la función:

In [279]:
def resum(x):
    if x.ndim>1:
        print('error:el array tiene más de una dimensión')
    else:
        a=round(np.mean(x),2)
        print('media aritmetica',a)
        b=np.round(abs(np.subtract(x,a)),2)
        print('desviación respecto a la media aritmetica',b)
        c=round(np.var(x),2)
        print('varianza',c)
        d=round(np.std(x),2)
        print('desviación típica',d)
        values,counts = np.unique(x, return_counts=True)
        e=values[counts == np.max(counts)]
        print('moda',e)
        f=round(np.median(x),2)
        print('mediana',f)
        
    return


Considerando un array random arr:

In [280]:
arr=random.randint(20,size=(7))
print(arr)

[11 18 13 13 13 15 10]


Llamamos la función para el array arr:

In [281]:
resum(arr)

media aritmetica 13.29
desviación respecto a la media aritmetica [2.29 4.71 0.29 0.29 0.29 1.71 3.29]
varianza 5.92
desviación típica 2.43
moda [13]
mediana 13.0


## Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

Creamos la función:

In [273]:
def my_function(n):
    return random.randint(100,size=(n,n))


Llamamos la función para crear el quadrat arr1:

In [274]:
arr1=my_function(6)
print(arr1)

[[98 46 98 29 36 24]
 [96 48  5 20 89 96]
 [58 15 72 36 65 53]
 [86 31  4 48 61 81]
 [54 25 10 64 74 88]
 [46  5  2 34 41 70]]


## Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.



Creamos la función :

In [282]:
def my_function(x):
    
    a=np.sum(x,axis=1)
    print('la suma de las filas es',a)
    
    b=np.sum(x,axis=0)
    print('la suma de las columnas es',b)
    return 


Considerando un array random de 2 dimensiones:

In [283]:
m=int(input('entra 1ª dimensión: '))
n=int(input('entra 2ª dimensión: '))
arr2=random.rand(m,n)
print(arr2)

entra 1ª dimensión: 5
entra 2ª dimensión: 4
[[0.66755188 0.51116143 0.21758415 0.34303293]
 [0.32868017 0.33258692 0.09668227 0.28766912]
 [0.44889377 0.21806202 0.26431255 0.42057238]
 [0.56507545 0.11816053 0.01879904 0.01032742]
 [0.71025846 0.1988442  0.83008941 0.50391512]]


Llamamos la función para el array arr2:

In [284]:
my_function(arr2)

la suma de las filas es [1.73933039 1.04561848 1.35184071 0.71236243 2.24310719]
la suma de las columnas es [2.72045972 1.37881509 1.42746741 1.56551697]


## Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.



El objetivo es calcular el coeficiente de correlación de dos variables, representadas abajo por dos arrays random de una dimensión cada uno, Alfa y Beta:

In [231]:
alfa=random.randint(10,size=(6))
beta=random.randint(10,size=(6))
print(alfa)
print(beta)


[7 4 7 4 8 0]
[6 8 7 8 4 3]


Creamos la función:

In [268]:
def coef_correlacion(a,b):   
    
#Calculamos la media aritmética de cada variable    
    media_a=np.mean(a)
    media_b=np.mean(b)
 
   
#Calculamos la covarianza
    lista_a_b= [(i-media_a)*(j-media_b) for i,j in zip(a,b)]
    cov=(np.sum(lista_a_b)/len(lista_a_b))

#Calculamos la varianza de cada variable    
    lista_a=[(i-media_a)*(i-media_a) for i in a]
    lista_b=[(i-media_b)*(i-media_b) for i in b]

    var_a=np.sum(lista_a)/len(lista_a)
    var_b=np.sum(lista_b)/len(lista_b)
    
#Calculamos el coeficiente de correlación
    coef=round(cov/(np.sqrt(var_a*var_b)),5)
    print('el coeficiente de correlación es',coef)

    return


LLamamos la función para las variables Alfa y Beta:

In [269]:
coef_correlacion(alfa,beta)

el coeficiente de correlación es 0.22499


Comprobamos el resultado con la función de Numpy:

In [245]:
x=np.corrcoef(alfa,beta)
print(x)

[[1.         0.22498852]
 [0.22498852 1.        ]]
